### PR TITLE
Add exist() assertion

### PR DESCRIPTION
**Pull request by qsona**
same issue as #22, but added some tests and updated README.

### CODE REVIEW

**Comment by rauchg** [comment]
"exist" is a hard to define concept in JS. Arguably the only thing that doesn't _exist_ is `undefined`.

**Comment by javidjamae** [comment]
@rauchg other libraries like Chai seem to do it very similarly (i.e. not null, not undefined): https://github.com/chaijs/chai/blob/e088727baba03f3787586974888fa2a4e2f7b817/lib/chai/core/assertions.js#L370-L394

Based on the comments here, it seems like a bunch of people are looking for this functionality: 
https://github.com/Automattic/expect.js/pull/22

Could you perhaps give better feedback on why it was closed and what you would expect of a _correct_ PR that would be accepted?

**Comment by ripter** [comment]
+1

**Comment by atian25** [comment]
any plan at this ?

**Pull request closed without merging**
